# grafana/datasources/datasources.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_ds_visits
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false