# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'webserver'
    static_configs:
      - targets: ['webserver:8080']
    metrics_path: /metrics

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: /metrics