# docker-compose.yml
version: '3.8'

services:
  # Load Balancer e punto di ingresso
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - visit-counter
    networks:
      - app-net

  # Applicazione Node.js (ora scalata a 3 repliche)
  visit-counter:
    build: .
    deploy:
      replicas: 3 # Avvia 3 istanze del nostro server
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-net

  # Database in-memory per lo stato condiviso
  redis:
    image: "redis:alpine"
    networks:
      - app-net

  # Prometheus per il monitoraggio
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/nginx/prometheus.yml
    depends_on:
      - visit-counter
    networks:
      - app-net

  # Grafana per la visualizzazione
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-net

volumes:
  grafana_data:

networks:
  app-net:
    driver: bridge